### ISSUE TITLE
How to work with siterank in pycharm ?

### ISSUE THREAD

**Issue by Jainu-s** [prahladyeri/siterank#1]
I imported the library siterank and there is no documentation on how to work in pycharm or any other IDLE can you please provide code for it. Thank you.

**Comment by mytja** [comment]
This code works only with command line, and is also outdated
I recommend you my library which offeres even more: https://github.com/mytja/SiteRank-Alexa

**Comment by prahladyeri** [comment]
Alexa ranking API is now retired. Suggest you to try the latest build (1.0.8) which uses SimilarWeb instead. And yeah, nothing special needed for pycharm, treat this like just another python package.
